services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktracker_db
    environment:
      SA_PASSWORD: "StrongPassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tasktracker_backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tasktracker_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
