apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-db
  labels:
    app: tasktracker
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker
      component: database
  template:
    metadata:
      labels:
        app: tasktracker
        component: database
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tasktracker-db-service
  labels:
    app: tasktracker
    component: database
spec:
  selector:
    app: tasktracker
    component: database
  ports:
  - port: 1433
    targetPort: 1433
    name: mssql
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  SA_PASSWORD: U3Ryb25nUGFzc3cwcmQh  # Base64 encoded "StrongPassw0rd!"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi