apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktracker-db
  labels:
    app: tasktracker
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasktracker
      component: database
  template:
    metadata:
      labels:
        app: tasktracker
        component: database
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "tasktracker"
        - name: POSTGRES_USER
          value: "tasktracker"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U tasktracker -d tasktracker
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U tasktracker -d tasktracker
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tasktracker-db-service
  labels:
    app: tasktracker
    component: database
spec:
  selector:
    app: tasktracker
    component: database
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: U3Ryb25nUGFzc3cwcmQh  # Base64 encoded "StrongPassw0rd!"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi